### ISSUE TITLE
select/bsp-select.tmpl.html 404 (Not Found)

### ISSUE THREAD

**Issue by hmendezm** [jrief/angular-bootstrap-plus#7]
Hi Guys,

First at all, thank you very much for developing this directive. I have a question.I am new in directive Do I need to copy the  bsp-select.tmpl.html? 

Best Regards
Hank

**Comment by jrief** [comment]
No.
Either you have to access it through other means, HTTP request, or add it to your existing code with
```
<script id="bsp-select.tmpl.html" type="text/ng-template">
```
