### ISSUE TITLE
Cannot read property 'addOptionElement' of null

### ISSUE THREAD

**Issue by hmendezm** [jrief/angular-bootstrap-plus#8]
Hi Guys,

So sorry me again. I copy the tmpl.html to my solution to make this directive to work but now I get this error. Any idea?

Best Regards
Hank

**Comment by m1nd53t** [comment]
I've had the same problem with angular 1.4, the fix is pretty easy in the bspOption directive, change the line that has the ```parentCtrl = ...``` to ```parentCtrl = ( !controllers[1] ) ? controllers[0] : controllers[1],```

**Comment by jrief** [comment]
thanks, can re please re-test
